### PR TITLE
Added more information to the readme

### PR DESCRIPTION
**Pull request by fakela**
Added more information on how to edit docs and make a pull request. To provide firsthand information to contributors

### CODE REVIEW

**Comment by fakela** [comment]
@rupa Please could you please review

**Comment by fakela** [comment]
> thanks for this.
> 
> per other PR, i'm inclined to move from rst to markdown with the README to obviate need to mention rst docs.
> 
> and I'd prefer not to emphasize/explain editing files directly in github. I don't think it's in scope for this documentation - the more "regular" docs about making a PR are welcome, tho :)

Alright, thanks for the review. I would change the README to a markdown file and work on the changes 👍

**Comment by rupa** [comment]
i've got a PR for rst -> md up (but not including your proposed changes) if you want to base things on that :)

**Comment by fakela** [comment]
Once the PR is merged I would include my proposed changes

**Pull request closed without merging**
