### PR TITLE
Fix links in readme

### PR DESCRIPTION
**Pull request by fakela**

### CODE REVIEW

**Comment by fakela** [comment]
@rupa could you please review

**Comment by rupa** [comment]
ah, woops, thanks for bringing this to our attention.

looks like we've mostly used markdown syntax but the README is `rst`.

The intent for this clause is a blockquote, with functioning link of course. Rather than fix this this way, Im inclined to make the README a `.md`

**Comment by fakela** [comment]
If I understand properly you want to change the README from `rst` to `.md`

**Comment by fakela** [comment]
There is actually a way to add the block quote in `rst`

**Comment by rupa** [comment]
yeah, sorry i wasn't clear - when conferring with the team, the preference was to to do markdown, for consistency, rather than fix this in restructured text terms. I'll close this one, as the links should be fixed now, and we can get the good bits of your other PR sorted :)

**Pull request closed without merging**
